import os

DEBUG = True
SQLALCHEMY_DATABASE_URI = os.environ.get("DATABASE_URI", "sqlite:///data.db")
SQLALCHEMY_TRACK_MODIFICATIONS = False
PROPAGATE_EXCEPTIONS = True
JWT_SECRET_KEY = os.environ["JWT_SECRET_KEY"]
SECRET_KEY = os.environ["APP_SECRET_KEY"]
UPLOADED_IMAGES_DEST = os.path.join("static", "images")
JWT_BLACKLIST_ENABLED = True
JWT_BLACKLIST_TOKEN_CHECKS = ["access", "refresh"]
JWT_TOKEN_LOCATION = ["cookies"]
JWT_ACCESS_COOKIE_PATH = ["/api"]
JWT_REFRESH_COOKIE_PATH = ["/token/refresh"]
JWT_COOKIE_CSRF_PROTECT = True
JWT_CSRF_CHECK_FORM = True
